title: Silver Oak Press
url: "https://silveroakpress.com"
title_image: "http://silveroakpress.com/images/home_img.jpg"

page_gen-dirs: true
page_gen:
  - data: 'processed_books'
    template: 'book_template'
    name: 'title'
    dir: 'books'

include: [lib/initializer.rb]
